### ISSUE TITLE
SharePoint Pipeline

### ISSUE THREAD

**Issue by rajaseg** [dataplane-app/dataplane#339]
Hi Team,
Thank you very much for the project.

I deployed the data plane using docker-compose. Is there any sample pipeline configuration? I wanted to create a SharePoint pipeline to pull the data from SharePoint online.

**Comment by saul-data** [comment]
I will try find some time tomorrow to put together an example you can use.

**Comment by rajaseg** [comment]
> I will try find some time tomorrow to put together an example you can use.

@saul-data, Thank you very much.

**Comment by saul-data** [comment]
@rajaseg  I haven't yet finished but these recipes should help you get started. 

Register an azure app: https://recipes.dataplane.app/office-365/register-an-azure-app
Authenticate with Graph API: https://recipes.dataplane.app/office-365/sharepoint-api

**Comment by rajaseg** [comment]
> @rajaseg I haven't yet finished but these recipes should help you get started.
> 
> Register an azure app: https://recipes.dataplane.app/office-365/register-an-azure-app Authenticate with Graph API: https://recipes.dataplane.app/office-365/sharepoint-api

@saul-data, I tried to install `requests==2.28.1` as mentioned in the SharePoint API recipe. But no luck. It is in a Running state.
Please find the below image for reference.

![image](https://user-images.githubusercontent.com/633479/182523519-66faa37b-e2e3-4221-9039-8932623b54b6.png)

**Comment by saul-data** [comment]
@rajaseg thanks - are you running Dataplane with the docker-compose setup? If so, if you have Docker Desktop can you show that all the services are running? Which operating system are you on? It may be a networking issue in docker compose, I'll make a note, I think we need to create a single docker image for a simpler setup.

**Comment by rajaseg** [comment]
> @rajaseg thanks - are you running Dataplane with the docker-compose setup? If so, if you have Docker Desktop can you show that all the services are running? Which operating system are you on? It may be a networking issue in docker compose, I'll make a note, I think we need to create a single docker image for a simpler setup.

@saul-data, Yes I am running Dataplane using docker-compose in the docker-swarm environment. It's behind Caddy proxy. Please find the docker-compose below.

```
version: '3.7'

services:
  postgres:
    image: timescale/timescaledb:2.5.1-pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Password123!"
      POSTGRES_DB: "dataplane"
    volumes:
      - /mnt/dataplanedb:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      retries: 5
    networks:
      - caddy
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  
  nats:
    image: nats:2.7.4-scratch
    command:
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
    networks:
      - caddy
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  nats-r:
    image: nats:2.7.4-scratch
    command:
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
      - "--routes"
      - "nats://nats:6222"
    networks:
      - caddy
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  dataplane:
    image: dataplane/dataplane:latest
    ports:
      - "9001:9001"
    volumes:
      - /mnt/dataplane:/dataplane/code-files/
    environment:
      DP_CODE_FOLDER: "/dataplane/code-files/"
      secret_db_host: postgres
      secret_db_user: postgres
      secret_db_pwd: "Manimmahps123!"
      secret_db_ssl: "disable"
      secret_db_port: "5432"
      secret_db_database: "dataplane"
      secret_jwt_secret: "45feb20d-06c7-42a5-bdc5-cdfa60b1b39d"
      secret_encryption_key: "Lt1nk%Nabcd5S&2VvMpCOiKMXUFo!H9P"
      DP_DATABASE: "timescaledb"
      DP_PORT: "9001"
      DP_NATS: "nats://nats:4222, nats://nats-r_1:4222, nats://nats-r_2:4222"
      DP_MODE: "development"
      DP_DEBUG: "true"
      DP_DB_DEBUG: "false"
      DP_MQ_DEBUG: "false"
      DP_METRIC_DEBUG: "false"
      DP_SCHEDULER_DEBUG: "false"
      DP_CLEANTASKS_DAYS: "60"
      DP_REMOVELOGS_DAYS: "60"
    networks:
      - caddy
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  dataplane-worker:
    image: dataplane/dataplane-worker-python:latest
    volumes:
      - /mnt/dataplane:/dataplane/code-files/
    environment:
      DP_CODE_FOLDER: "/dataplane/code-files/"
      secret_db_host: postgres
      secret_db_user: postgres
      secret_db_pwd: "Password123!"
      secret_db_ssl: "disable"
      secret_db_port: "5432"
      secret_db_database: "dataplane"
      secret_jwt_secret: "45feb20d-06c7-42a5-bdc5-cdfa60b1b39d"
      DP_DATABASE: "timescaledb"
      DP_NATS: "nats://nats:4222, nats://nats-r_1:4222, nats://nats-r_2:4222"
      DP_MODE: "development"
      DP_DEBUG: "true"
      DP_DB_DEBUG: "false"
      DP_MQ_DEBUG: "false"
      DP_METRIC_DEBUG: "false"
      DP_SCHEDULER_DEBUG: "false"
      DP_WORKER_HEARTBEAT_SECONDS: "1"
      DP_WORKER_GROUP: "python_1"
      DP_WORKER_CMD: "/bin/sh"
      DP_WORKER_TYPE: "container"
      DP_WORKER_LB: "roundrobin"
      DP_WORKER_ENV: "Development"
      DP_WORKER_PORT: "9005"
      DP_WORKER_LANGUAGES: "Python"
      DP_WORKER_LOAD_PACKAGES: "Python"
    networks:
      - caddy
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

volumes: 
  dataplanedb:
    driver: "local"
  dataplane:
    driver: "local"   
networks:
  caddy:
    external: true
```
All the services are running fine. Please find the below image for your reference.

![image](https://user-images.githubusercontent.com/633479/182525980-296acf25-53a0-4125-b8f3-468d47a63087.png)
